server:
  port: 8080
spring:
#  mvc:   #静态文件   -- 可以不用配 引入了依赖 spring-boot-starter-thymeleaf
#    static-path-pattern: /static/**
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tang?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 25
      idle-timeout: 60000
      max-lifetime: 90000
      auto-commit: true
      pool-name: DatebookHikariCP_order
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true